version: "3.7"
services:
  tidy:
    build: tidy
    volumes:
    - myorgfiles:/tmp/scratch
  pandoc_cleanup:
    build: pandoc_cleanup
    volumes:
    - myorgfiles:/tmp/scratch
  emacs_cleanup:
    build: emacs_cleanup
    volumes:
    - myorgfiles:/tmp/scratch
  pandoc:
    image: pandoc/core@sha256:771842ce6f661785e0e12931f82ea64046d70fa48ea5cff480492d79ab3b8ff1
    volumes:
    - myorgfiles:/tmp/scratch
  flask-receive-html:
    build: receive
    ports:
    - 127.0.0.1:8989:5000
    restart: unless-stopped
    working_dir: /
    volumes:
    - myorgfiles:/tmp/scratch
    - /var/run/docker.sock:/var/run/docker.sock
volumes:
  myorgfiles:
    name: myorgfiles
