version: "3.7"
services:
  tidy:
    build: tidy
    volumes:
    - myorgfiles:/tmp/scratch
  pandoc_cleanup:
    build: pandoc_cleanup
    volumes:
    - myorgfiles:/tmp/scratch
  emacs_cleanup:
    build: emacs_cleanup
    volumes:
    - myorgfiles:/tmp/scratch
  pandoc:
    image: pandoc/core@sha256:5173eb664e07c571939bc702b2c5420e2b715fd30b6f63ac0aa7610bd9b57107
    volumes:
    - myorgfiles:/tmp/scratch
  flask-receive-html:
    build: receive
    ports:
    - 127.0.0.1:8989:5000
    restart: unless-stopped
    working_dir: /
    volumes:
    - myorgfiles:/tmp/scratch
    - /var/run/docker.sock:/var/run/docker.sock
volumes:
  myorgfiles:
    name: myorgfiles
